### ISSUE TITLE
[Bug] It's not Working

### ISSUE THREAD

**Issue by brunocalado** [sparkcity/fvtt-eij#11]
Hi.

This is gerenating lots of errors. It's not even possible to open the actor sheet.
![image](https://user-images.githubusercontent.com/4999783/154823949-1fcf5418-02d7-4a0c-b7e5-c9c4ae1fcb8f.png)

![image](https://user-images.githubusercontent.com/4999783/154823955-7bed7bd1-7f67-405c-98d7-15ae4772d552.png)

**Comment by zachmmeyer** [comment]
Thanks for making this! Hopefully the issue can get sorted at some point. I'm going to try and learn more about Foundry, maybe I'll be able to submit a fix in the future.

**Comment by sparkcity** [comment]
> 

So I've been trying to replicate this issue with no success. On the local machine, it works exactly as it should. I'm going to do some more digging to try to figure out why on earth it's not working outside of the local environment. It might be a path that was made exact instead of relative, but will fix when I can.

**Comment by zachmmeyer** [comment]
For what it's worth, I can open the actor sheet on mine. I can't right click and assign it to a person though.

![image](https://user-images.githubusercontent.com/34407561/161313279-56deb98f-ac57-4f93-995f-39d9a97d643f.png)

I cloned this and tried to play with it a bit, but I unfortunately have no idea what I'm doing.
That's the only issue I'm having: assigning sheets to players and keeping them hidden from others.

**Comment by kreynoldson** [comment]
Unfortunately, I'm running into the same issue. Can't right-click on Actors to assign or delete. V9- Build 280 of FVTT. 

Appreciate you making it regardless.
